### ISSUE TITLE
Выводить текст ошибки при регистрации

### ISSUE THREAD

**Issue by tre3p** [hexlet-components/project-java-task-manager-frontend#5]
Если зарегистрироваться с дубликатом email, то фронт отобразит статус-код ошибки, а не текст.
Хотелось бы, чтобы фронт перехватывал сообщение с бэка и выводил его
![image](https://user-images.githubusercontent.com/68253357/150972937-3b462d20-8649-4a89-9660-64d6ea2ad953.png)

**Comment by dzencot** [comment]
Тут может быть проблема в том, что на бэке не будет реализована передача сообщения. Поговорю с автором проекта, если на бэке это требование будет, то и на фронте можно сделать.
