### ISSUE TITLE
Не работает фильтр при нажатии галочки "Только мои задачи"

### ISSUE THREAD

**Issue by AndreiSerov** [hexlet-components/project-java-task-manager-frontend#8]
ФР:
![изображение](https://user-images.githubusercontent.com/57676155/221594233-1d0bc2eb-092a-4a21-a31f-b50ca11a2ea9.png)

ОР: должен добавиться параметр пути authorId=<id текущего пользователя>

**Comment by sgmdlt** [comment]
@dzencot

**Comment by dzencot** [comment]
Поправил https://github.com/hexlet-components/project-java-task-manager-frontend/commit/382b85a0b5a73ca93e0a9c8e7ccbef9a6d3140a9
